/**
 * render.js — Page rendering engine.
 * Do NOT edit this file. All content is in data.js.
 */

/* ── Helpers ── */
const $ = id => document.getElementById(id);
const esc = s => String(s).replace(/&(?![a-z]+;)/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/* ── Profile ── */
function renderProfile() {
  const p = PROFILE;
  const initials = p.name.split(' ').map(w => w[0]).join('');
  const btns = p.buttons.map(b =>
    `<a href="${b.url}" target="_blank" class="btn btn-${b.type === 'solid' ? 'solid' : 'outline'}">${b.label}</a>`
  ).join('');

  $('profile-root').innerHTML = `
    <div class="profile-section" id="about">
      <div class="avatar-wrap">
        <img class="avatar" src="${p.photo}" alt="${p.name}"
          onerror="this.style.display='none';this.nextElementSibling.style.display='flex';" />
        <div class="avatar-fallback">${initials}</div>
        <span class="avatar-status" title="Open to collaboration"></span>
      </div>
      <div>
        <h1 class="profile-name">${p.name}</h1>
        <p class="profile-role">${p.role}</p>
        <p class="profile-bio">${p.bio}</p>
        <div class="profile-meta">
          <span class="meta-item">
            <svg width="13" height="13" viewBox="0 0 16 16" fill="currentColor">
              <path d="M8 1a5.5 5.5 0 00-5.5 5.5c0 3.26 4.75 8.08 5.15 8.48a.5.5 0 00.7 0C8.75 14.58 13.5 9.76 13.5 6.5A5.5 5.5 0 008 1zm0 7.5a2 2 0 110-4 2 2 0 010 4z"/>
            </svg>
            ${p.location}
          </span>
          <span class="meta-item">
            <svg width="13" height="13" viewBox="0 0 16 16" fill="currentColor">
              <path d="M0 4v7.5c0 .83.67 1.5 1.5 1.5H14.5c.83 0 1.5-.67 1.5-1.5V4l-8 5-8-5zm0-1.5l8 5 8-5H0z"/>
            </svg>
            <a href="mailto:${p.email}">${p.email}</a>
          </span>
        </div>
        <div class="btn-row">${btns}</div>
      </div>
    </div>`;
}

/* ── Stats ── */
function renderStats() {
  if (!STATS.enabled) return;
  const cols  = STATS.items.length;
  const cells = STATS.items.map(s =>
    `<div class="stat-cell"><div class="stat-n">${s.number}</div><div class="stat-l">${s.label}</div></div>`
  ).join('');
  $('stats-root').innerHTML =
    `<div class="stats-row" style="grid-template-columns:repeat(${cols},1fr)">${cells}</div>`;
}

/* ── Section content renderers ── */
const RENDERERS = {
  interests: {
    title: "Research Interests",
    render() {
      if (!INTERESTS.enabled) return null;
      const tags  = INTERESTS.tags.map(t =>
        `<span class="tag tag-${t.color}">${t.label}</span>`).join('');
      const quote = INTERESTS.quote
        ? `<div class="quote"><p>${INTERESTS.quote}</p></div>` : '';
      return `<div class="tag-cloud">${tags}</div>${quote}`;
    }
  },

  publications: {
    title:   "Publications",
    seeAll:  () => PUBLICATIONS.seeAllUrl,
    seeLabel:"All papers →",
    render() {
      if (!PUBLICATIONS.enabled) return null;
      const cards = PUBLICATIONS.items.map(p => `
        <div class="pub-card">
          <div class="pub-meta-row">
            <span class="pub-venue">${p.venue}</span>
            <span class="pub-year">${p.year}</span>
          </div>
          <div class="pub-title">${p.title}</div>
          <div class="pub-authors">${p.authors}</div>
        </div>`).join('');
      return `<div class="pub-list">${cards}</div>`;
    }
  },

  experience: {
    title: "Experience & Education",
    render() {
      if (!EXPERIENCE.enabled) return null;
      const dotClass = { current: '', past: ' dim', degree: ' gold' };
      const items = EXPERIENCE.items.map(e => `
        <div class="tl-item">
          <div class="tl-year">${e.year}</div>
          <div class="tl-spine">
            <div class="tl-dot${dotClass[e.dot] || ''}"></div>
            <div class="tl-line"></div>
          </div>
          <div>
            <div class="tl-title">${e.title}</div>
            <div class="tl-where">${e.where}</div>
            ${e.desc ? `<div class="tl-desc">${e.desc}</div>` : ''}
          </div>
        </div>`).join('');
      return `<div class="timeline">${items}</div>`;
    }
  },

  blog: {
    title:    "Blog",
    seeAll:   () => "blog/index.html",
    seeLabel: "All posts →",
    render() {
      if (!BLOG.enabled) return null;
      const cards = BLOG.items.map(p => {
        if (p.placeholder) return `
          <div class="blog-card placeholder">
            <div class="ph-icon">✍️</div>
            <div class="ph-text">More posts coming soon</div>
          </div>`;
        return `
          <div class="blog-card" onclick="location.href='${p.url}'" style="cursor:${p.url === '#' ? 'default' : 'pointer'}">
            <div class="blog-top">
              <div class="blog-date">${p.date}</div>
              <div class="blog-topic ${p.color !== 'blue' ? p.color : ''}">${p.topic}</div>
            </div>
            <div class="blog-title">${p.title}</div>
            <div class="blog-excerpt">${p.excerpt}</div>
            ${p.url !== '#' ? `<a href="${p.url}" class="blog-read">Read post →</a>` : `<span class="blog-read" style="opacity:.4">Coming soon</span>`}
          </div>`;
      }).join('');
      return `<div class="blog-grid">${cards}</div>`;
    }
  },

  contact: {
    title: "Find Me Online",
    render() {
      if (!CONTACT.enabled) return null;
      const cards = CONTACT.items.map(c =>
        `<a href="${c.url}" target="_blank" class="link-card">
           <span class="link-icon">${c.icon}</span>${c.label}
         </a>`).join('');
      return `<div class="links-grid">${cards}</div>`;
    }
  },
};

/* ── Nav meta ── */
const NAV_META = {
  interests:    { id: "research",     label: "Research"  },
  publications: { id: "publications", label: "Papers"    },
  experience:   { id: "experience",   label: "Experience"},
  blog:         { id: "blog",         label: "Blog"      },
  contact:      { id: "contact",      label: "Contact"   },
};

/* ── Boot ── */
document.addEventListener('DOMContentLoaded', () => {
  renderProfile();
  renderStats();

  const main    = $('main-root');
  const navList = $('nav-links');

  SECTIONS_ORDER.forEach(key => {
    const cfg  = RENDERERS[key];
    const meta = NAV_META[key];
    const html = cfg.render();
    if (!html) return;

    // Nav item
    const li = document.createElement('li');
    li.innerHTML = `<a href="#${meta.id}">${meta.label}</a>`;
    navList.appendChild(li);

    // Section element
    const seeAllUrl   = cfg.seeAll ? cfg.seeAll() : null;
    const seeAllHtml  = seeAllUrl
      ? `<a href="${seeAllUrl}" class="see-all">${cfg.seeLabel}</a>` : '';

    const sec = document.createElement('section');
    sec.className = 'section';
    sec.id = meta.id;
    sec.innerHTML = `
      <div class="section-head">
        <h2 class="section-title">${cfg.title}</h2>
        ${seeAllHtml}
      </div>
      ${html}`;
    main.appendChild(sec);
  });

  // Highlight active nav link on scroll
  const sections = document.querySelectorAll('section[id]');
  const observer = new IntersectionObserver(entries => {
    entries.forEach(e => {
      const link = document.querySelector(`#nav-links a[href="#${e.target.id}"]`);
      if (link) link.classList.toggle('active', e.isIntersecting);
    });
  }, { threshold: 0.4 });
  sections.forEach(s => observer.observe(s));
});
